#!/bin/bash
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="git,nvim,alacritty,sway,tmux,wezterm,bash,asdf"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
